{% set version = "1.0-8" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-mlmrev
  version: {{ version|replace("-", "_") }}

source:
  fn: mlmRev_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/mlmRev_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/mlmRev/mlmRev_{{ version }}.tar.gz
  sha256: d57f3ff5d49e5f0079d4367cdbc1a273f48d8ce8f03bb82bb5f90606bfb2c452

build:
  noarch: generic
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-lme4
  run:
    - r-base
    - r-lme4

test:
  commands:
    - $R -e "library('mlmRev')"  # [not win]
    - "\"%R%\" -e \"library('mlmRev')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=mlmRev
  license: GPL (>= 2)
  summary: |
    Data and examples from a multilevel modelling software review as well as other well-known
    data sets from the multilevel modelling literature.
  license_family: GPL3

extra:
  recipe-maintainers:
    - conda-forge/r
    - johanneskoester
    - bgruening
