appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: S9gJ2rGt8gxUr53HlFIY893Id/yi9SYKWmM66R5l97gKxz2vE/WfxjYv5IQ9CqEXrWjTBrGULQwmNo27ReMbmjLOf5/0yJeuIThOodm7uJPlttUaSYU6rbtKBUhW8BshhpSfJcttRObOBjCFAxfLYGefguYKnjIaKd84BQteu2nah/FiZWsWNE8uG2fpzu/EPzZmic8IfDnqgmD4vq7HocgZ2PDszblgdpjxqfeftNHTFSGdpCc49qb6la5VhmdoKHlzaDWpVXg8IqXVJCWS95m/LO6WxJ/pWeMyf7PTJnplQLu15QKm/J5lDhVahKXX6HHYyFi1X1I65TFWYyX8yoaRZfM7i573NJdIitC9jcZi0sTi+ZU0rq+cTkQFPi8GaMXBmjyEdNadt5icuRYkDXGCLlqP/qoy/0ywQVV+mscoKBC4nbOKDoztS9s8/GgrAjBmRr0qVZSURAFVqATC3Y572JEzqra7/LuZPf8/7nH7LMbX1ibd4A7yNt6CN8F88N4w/DpkW9Sxp2PwZ8NQZh4LhyXMaC6CbHAgDDYyzMlOf0k5ZF+qugieG1MCUzrShb3Mnp6D90In2BQbKjjIzn/4qCM3/6jn8mQFvoznDY3T8yjuIcN6unKtY1ydsk1F4e0E/05PU3rR6XD8aW5Sx5tMdk95pv8AH8NVuMuVBiI=}
